config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :posts do
      resources :comment, only: [:new, :create]
      resources :like, only: [:create]
      resources :book_mark, only: [:create]

      # RESOURCE, SCOPE
      # /CONTROLLERS/:ID/METHOD
      member do
        delete 'delete', to: 'posts#destroy_post_waiting_admin_confirm'
        post 'confirm', to: 'posts#confirm_post'
        post 'cancel', to: 'posts#cancel_post'
      end

      # /CONTROLERS/METHOD
      collection do
        get :bookmarked, to: 'posts#bookmarked'
        get :liked, to: 'posts#liked'
        get :confirming, to: 'posts#confirming'
        get :waiting_confirmations , to: 'posts#waiting_confirmations'
        get :publiced , to: 'posts#publiced'
      end
    end

    namespace :standard do
      resources :home
    end

    devise_scope :user do
      get 'password/change', to: 'standard/change_info#change_password', as: :change_password
      put 'password/change', to: 'standard/change_info#change_password_put', as: :change_password_put
      get 'profile', to: 'standard/home#show', as: :profile
    end

    devise_for :user, path: 'auth',
      path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                    confirmation: 'comfirm', unlock: 'unblock', registration: 'register',
                    sign_up: 'sign-up'
                  },
      controllers:{registrations: 'user/registrations',
                    sessions: 'user/sessions',
                    passwords: 'user/passwords',
                    unlocks: 'user/unlocks',
                    confirmation: 'user/confirmations'
                  }
  end
  get '/:locale' => 'standard/home#index', as: :root
end

app/views/layouts/home_layout/_comment_form.html.slim
  .form-group
    = f.text_field :content, autofocus: true, autocomplete: "content", class: 'form-control input-md'
      br
    =f.submit "#{I18n.t(".actions.post.comment.button")}", class: 'btn btn-primary'

app/views/layouts/home_layout/_footer.html.slim
footer.container
  p
    | © Company 2017-2020

app/views/layouts/home_layout/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  a.navbar-brand
  = link_to root_path
    i.fa.fa-home
  a.navbar-brand
  = link_to bookmarked_posts_path
    i.fa.fa-heart
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
    span.navbar-toggler-icon

  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li#nav1.nav-item.dropdown
        a.nav-link.dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
         | #{I18n.t(".actions.user.management.title")}
        #drop1.dropdown-menu.text-center aria-labelledby="dropdown01"
          = link_to  "#{I18n.t(".actions.user.management.profile")}", profile_path ,  class: 'dropdown-item'
          = link_to  "#{I18n.t(".actions.user.management.change_profile")}", edit_user_registration_path, class: 'dropdown-item'
          = link_to  "#{I18n.t(".actions.user.management.change_password")}", change_password_path, class: 'dropdown-item'
          = link_to "#{I18n.t(".actions.user.management.sign_out")}", destroy_user_session_path, method: :delete, class: 'dropdown-item', data: { confirm: "Are you sure ?" }
      li#nav2.nav-item.dropdown
        a.nav-link.dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
         | #{I18n.t(".actions.post.management")}
        #drop2.dropdown-menu.text-center aria-labelledby="dropdown01"
          = link_to "#{I18n.t(".actions.post.create.new")}", new_post_path, class: 'dropdown-item'
          = link_to "#{I18n.t(".actions.post.show.my_post.public")}", publiced_posts_path, class: 'dropdown-item'
          - if current_user.standard?
            = link_to "#{I18n.t(".actions.post.show.my_post.waiting_confirm")}", confirming_posts_path, class: 'dropdown-item'
          - if current_user.adminnistrator?
            = link_to "#{I18n.t(".actions.post.show.my_post.confirm")}", waiting_confirmations_posts_path, class: 'dropdown-item'
      li#nav2.nav-item.dropdown
        a.nav-link.dropdown-toggle data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
         | #{I18n.t(".actions.locale.title")}
        #drop2.dropdown-menu.text-center aria-labelledby="dropdown01"
          p
            = link_to "#{I18n.t(".actions.locale.en")}", locale:"en", class: 'dropdown-item'
          p
            = link_to "#{I18n.t(".actions.locale.vi")}", locale:"vi", class: 'dropdown-item'
    = render "layouts/home_layout/search_form"

app/views/layouts/home_layout/_paginate_item.html.slim
.row
  .col-md-4
    == pagy_bootstrap_nav(pagy)

app/views/layouts/home_layout/_search_form.html.slim
= search_form_for @q, url: root_path, method: :get, class: 'right' do |f|
  = f.label :content_or_title_cont, class:'sr-only'
  = f.search_field :content_or_title_cont, class:'form-controlmr-sm-2'

  = f.submit