config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    resources :posts do
      resources :comment, only: [:new, :create]
      resources :like, only: [:create]
      resources :book_mark, only: [:create]

      # RESOURCE, SCOPE
      # /CONTROLLERS/:ID/METHOD
      member do
        delete 'delete', to: 'posts#destroy_post_waiting_admin_confirm'
        post 'confirm', to: 'posts#confirm_post'
        post 'cancel', to: 'posts#cancel_post'
      end

      # /CONTROLERS/METHOD
      collection do
        get :bookmarked, to: 'posts#bookmarked'
        get :liked, to: 'posts#liked'
        get :confirming, to: 'posts#confirming'
        get :waiting_confirmations , to: 'posts#waiting_confirmations'
        get :publiced , to: 'posts#publiced'
      end
    end

    namespace :standard do
      resources :home
    end

    devise_scope :user do
      get 'password/change', to: 'standard/change_info#change_password', as: :change_password
      put 'password/change', to: 'standard/change_info#change_password_put', as: :change_password_put
      get 'profile', to: 'standard/home#show', as: :profile
    end

    devise_for :user, path: 'auth',
      path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret',
                    confirmation: 'comfirm', unlock: 'unblock', registration: 'register',
                    sign_up: 'sign-up'
                  },
      controllers:{registrations: 'user/registrations',
                    sessions: 'user/sessions',
                    passwords: 'user/passwords',
                    unlocks: 'user/unlocks',
                    confirmation: 'user/confirmations'
                  }
  end
  get '/:locale' => 'standard/home#index', as: :root
end

app/models/post.rb
class Post < ApplicationRecord
  enum status_active: {disactive: 0,confirm: 1, active: 2}
  has_one_attached :cover_image
  belongs_to :user
  has_many :likes
  has_many :users, through: :likes
  has_many :bookmarks
  has_many :users , through: :bookmarks
  has_many :comments
  has_many :users, through: :comments
  validates :title , presence: true
  validates :content , presence: true
  validates :status_active , presence: true, inclusion: {in:status_actives.keys}
  validates :cover_image, presence: true
  # scope :search_for_title, -> (search){ where("title LIKE ?", "%#{search}%") if search.present?}
  # scope :search_for_content, ->(search) { where("content LIKE ?", "%#{search}%") if search.present?}
  # Ex:- scope :active, -> {where(:active => true)}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/controllers/posts_controller.rb
class PostsController < DashboardController
  # def index
  #   @pagy, @post = pagy(Post.active, items: 3)
  #   @comment = Comment.new
  # end

  def new
    authorize @post = Post.new
  end

  def create
      @post, @message = post_service.create
      flash[:success] = @message
      redirect_to new_post_path
  end

  def edit
     @post = post_service.find_post
     authorize @post
  end

  def update
      post = post_service.find_post
      post_service.update(post)
      flash[:success] = I18n.t(".post.update.success")
      redirect_to edit_post_path
    rescue Exception => e
      flash[:error] = "error: #{e.message}"
      render edit_post_path
  end

  def show
    @comment = Comment.new
   authorize @post = post_service.find_post
  end

  def destroy
    authorize @post = post_service.find_post
    @post.destroy
    post_service.post_destroy
    post_service.like_destroy
    post_service.bookmark_destroy
    post_service.comment_destroy
    flash[:success] = I18n.t(".post.destroyed.success")
    redirect_to publiced_posts_path
  end

  def destroy_post_waiting_admin_confirm
    authorize @post = post_service.find_post
    @post.destroy
    flash[:success] = I18n.t(".post.destroyed.success")
    redirect_to confirming_posts_path
  end

  def bookmarked
    authorize post = post_service.posts_bookmarked
    @pagy, @post = pagy(post , items: 3)
  end

  def liked
    authorize post = post_service.posts_liked
    @pagy, @post = pagy(post, items: 3)
  end

  def confirming
    authorize post = post_service.find_post_confirm_of_current_user
    @pagy, @post = pagy(post, items: 3)
  end

  def publiced
    authorize post = post_service.find_post_active_of_current_user
    @pagy, @post = pagy(post, items: 3)
  end

  def waiting_confirmations
    authorize post = post_service.list_confirm
      @pagy, @post = pagy(post, items: 3)
  end

  def confirm_post
      authorize @post = post_service.find_post
      post_service.confirm_post(@post)
      flash[:success] = I18n.t(".post.active.success")
      redirect_to waiting_confirmations_posts_path
    rescue Exception => e
      flash[:error] = I18n.t(".post.active.errors")
      redirect_to waiting_confirmations_posts_path
  end

  def cancel_post
      authorize post = post_service.find_post
      post_service.cancel_post(post)
      flash[:success] = I18n.t(".post.cancel.success")
      redirect_to waiting_confirmations_posts_path
    rescue Exception => e
      flash[:error] = I18n.t(".post.cancel.errors")
      redirect_to waiting_confirmations_posts_path
  end

  private
  def parameters
    @params ||= Record::PostParams.new params
  end

  def post_service
    post_service ||= Record::PostService.new(current_user, parameters)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/standard/post_helper.rb
module Standard::PostHelper
end

app/views/posts/_form.html.slim
  = f.label :title,class: 'form-group col-md-8 control-label'
  = f.text_field :title, id: 'title', autocomplete: "title", class: 'form-control col-md-8 input-md', placeholder: "#{I18n.t(".input.post.title")}"
  br
  = f.label :content, class: 'form-group col-md-8 control-label'
  = f.text_area :content, size: "10x10", id: 'content', autocomplete: "content", class: 'form-control col-md-8 input-md', placeholder: "#{I18n.t(".input.post.content")}"
  br
  = f.label :cover_image, class: 'form-group col-md-8 control-label'
  = f.file_field :cover_image, id: 'cover_image', autocomplete: "cover_image", class: 'form-control col-md-4 input-md', placeholder: 'cover_image'
  br
  = f.submit "#{I18n.t(".actions.post.submit")}", class: 'btn btn-lg btn-primary btn-block col-md-1'

app/views/posts/bookmarked.html.slim
.container
  .row
    - @post.each do |post|
      .col-md-4
        h2 = post.title
        - if post.cover_image.attached?
          = image_tag  post.cover_image, heigh:"250px", width:"300px"
        p =post.content
        = link_to "#{I18n.t(".button.view_details")}",post , class: 'btn btn-secondary'

        = link_to  post_like_index_path(post.id), class: 'btn btn-primary', remote: true, method: :post
          | #{I18n.t(".button.like")}
          i.fa.fa-thumbs-up
          i class="like_#{post.id}"
            = post.likes.count
        = link_to post_book_mark_index_path(post.id), class: 'btn btn-danger', method: :post, remote: true
          | #{I18n.t(".button.bookmark")}
          i.fa.fa-heart
          i class="bookmark_#{post.id}"
            = post.bookmarks.count
  .row
    .col-md-4
      == pagy_bootstrap_nav(@pagy)


/ announcements:
/ models:
/ placeholders:
/ actions:
/ confirmations:

app/views/posts/confirming.html.slim
main role="main"
  .jumbotron
  .container
    .row
      - @post.each do |post|
        .col-md-4
          h2 =post.title
          - if post.cover_image.attached?
            = image_tag  post.cover_image, heigh:"250px", width:"300px"
          p =post.content
          = link_to "#{I18n.t(".button.view_details")}",post , class: 'btn btn-secondary'
          / - if current_user.adminnistrator?
          /   = link_to confirm_post_path(post.id), method: :post,class: 'btn btn-primary'
          /     | #{I18n.t(".button.agree")}
          /   = link_to cancel_post_path(post.id), method: :post, class: 'btn btn-danger'
          /   | #{I18n.t(".button.refuse")}
          / - if current_user.standard?
          = link_to delete_post_path(post), class: 'btn btn-danger', method: :delete
            | #{I18n.t(".button.delete")}
          = link_to edit_post_path(post), class: 'btn btn-primary'
              | #{I18n.t(".button.update")}
    .row
      .col-md-4
        == pagy_bootstrap_nav(@pagy)

app/views/posts/edit.html.slim
form.form-horizontal
fieldset
legend = I18n.t(".actions.post.update.title")

= form_for @post, url: post_path, html: { method: :patch}  do |f|
  = render 'form', f: f

  / = f.label :title, class: 'form-group col-md-4 control-label'
  / = f.text_field :title, id: "title",autocomplete: "title", class: 'form-control col-md-4 input-md', placeholder: 'title'
  / br
  / = f.label :content, class: 'form-group col-md-4 control-label'
  / = f.text_field :content, id: "content", autocomplete: "content", class: 'form-control col-md-4 input-md', placeholder: 'content'
  / br
  / - if @post.cover_image.attached?
  / = image_tag @post.cover_image, class: 'img img-2'
  / .clearfix
  / = f.label :cover_image, class: 'form-group col-md-4 control-label'
  / = f.file_field :cover_image, autocomplete: "cover_image", class: 'form-control col-md-4 input-md', placeholder: 'cover_image'
  / =f.submit "#{I18n.t(".actions.post.update.button")}", class: 'btn btn-lg btn-primary btn-block col-md-2'

app/views/posts/index.html.slim
.container
  .row
    - @post.each do |post|
      .col-md-6
          .blog-entry.ftco-animate.d-md-flex.fadeInUp.ftco-animated
            - if post.cover_image.attached?
              = image_tag  post.cover_image, heigh:"250px", width:"300px"
              .text.text-2.pl-md-4
                h4.mb-2
                  a = post.title
                .meta-wrap
                  p.meta
                    span
                      .i.fa.fa-calendar
                      | created_at :
                      = post.created_at
                    br
                    span
                      i.fa.fa-user
                      | author :
                      = post.user.username
                    br
                    span
                      i.fa.fa-comment
                      | comment :
                      = post.comments.count
                p.mb-4
                = link_to 'View details »', post, class: 'btn btn-secondary'

                = link_to post_like_index_path(post.id), class: 'btn btn-primary', method: :post, remote: true
                  | like
                  i.fa.fa-thumbs-up
                  i class="like_#{post.id}"
                    =post.likes.count
                = link_to post_book_mark_index_path(post.id), class: 'btn btn-danger', method: :post, remote: true
                  | bookmark
                  i.fa.fa-heart
                  i class="bookmark_#{post.id}"
                    = post.bookmarks.count
                = form_for @comment, url:post_comment_index_path(post_id: post.id), method: :post do |f|
                  .form-group
                    = f.text_field :content, autofocus: true, autocomplete: "content", class: 'form-control input-md-3'
                      br
                    =f.submit "comment", class: 'btn btn-primary'
  .row
    .col-md-4
      == pagy_bootstrap_nav(@pagy)

app/views/posts/liked.html.slim
.container
  .row
    - @post.each do |post|
      .col-md-4
        h2 =post.title
        - if post.cover_image.attached?
          = image_tag  post.cover_image, heigh:"250px", width:"300px"
        p =post.content
        = link_to "#{I18n.t(".button.view_details")}",post , class: 'btn btn-secondary'

        = link_to  post_like_index_path(post.id), class: 'btn btn-primary', remote: true, method: :post
          | #{I18n.t(".button.like")}
          i.fa.fa-thumbs-up
          i class="like_#{post.id}"
            = post.likes.count
        = link_to post_book_mark_index_path(post.id), class: 'btn btn-danger', method: :post, remote: true
          | #{I18n.t(".button.bookmark")}
          i.fa.fa-heart
          i class="bookmark_#{post.id}"
            = post.bookmarks.count
  .row
    .col-md-4
      == pagy_bootstrap_nav(@pagy)

app/views/posts/new.html.slim
form.form-horizontal
fieldset
legend = I18n.t(".actions.post.create.title")

= form_for @post, url: posts_path, html: { method: :post}  do |f|
  = render 'form', f: f

app/views/posts/publiced.html.slim
.container
  .row
    - @post.each do |post|
      .col-md-4
        h2 =post.title
        - if post.cover_image.attached?
          = image_tag  post.cover_image, heigh:"250px", width:"300px"
        p =post.content
        = link_to "#{I18n.t(".button.view_details")}",post , class: 'btn btn-secondary'

        = link_to  post_like_index_path(post.id), class: 'btn btn-primary', remote: true, method: :post
          | #{I18n.t(".button.like")}
          i.fa.fa-thumbs-up
          i class="like_#{post.id}"
            = post.likes.count
        = link_to post_book_mark_index_path(post.id), class: 'btn btn-danger', method: :post, remote: true
          | #{I18n.t(".button.bookmark")}
          i.fa.fa-heart
          i class="bookmark_#{post.id}"
            = post.bookmarks.count
        = link_to post_path(post), class: 'btn btn-danger', method: :delete
          | #{I18n.t(".actions.post.delete.button")}
        = link_to edit_post_path(post), class: 'btn btn-danger'
          | #{I18n.t(".actions.post.update.button")}
  .row
    .col-md-4
      == pagy_bootstrap_nav(@pagy)

app/views/posts/show.html.slim
.ftco-section
  .container
   .row.px-md-4
      .col-md-12
          .blog-entry.ftco-animate.d-md-flex.fadeInUp.ftco-animated
            - if @post.cover_image.attached?
              = image_tag  @post.cover_image, class:'img img-2'
              .text.text-2.pl-md-4
                h3.mb-2
                  a = @post.title
                p = @post.content
                .meta-wrap
                  p.meta
                    span
                      .i.fa.fa-calendar
                      | created_at :
                      = @post.created_at
                    br
                    span
                      i.fa.fa-user
                      | author :
                      = @post.user.username
                    br
                    span
                      i.fa.fa-comment
                      | comment :
                      = @post.comments.count
                p.mb-4
                = link_to post_like_index_path(@post.id), class: 'btn btn-primary', method: :post, remote: true
                  | like
                  i.fa.fa-thumbs-up
                  i class="like_#{@post.id}"
                    = @post.likes.count
                = link_to post_book_mark_index_path(@post.id), class: 'btn btn-danger', method: :post, remote: true
                  | bookmark
                  i.fa.fa-heart
                  i class="bookmark_#{@post.id}"
                    = @post.bookmarks.count
                = form_for @comment, url:post_comment_index_path(post_id: @post.id), method: :post do |f|
                  .form-group
                    = f.text_field :content, autofocus: true, autocomplete: "content", class: 'form-control input-md-3'
                      br
                    =f.submit "comment", class: 'btn btn-primary'

app/views/posts/waiting_confirmations.html.slim
.container
  .row
    - @post.each do |post|
      .col-md-4

        h2 =post.title
        p =post.content
        - if post.cover_image.attached?
          = image_tag  post.cover_image, heigh:"250px", width:"300px"
        p
          = link_to 'View details »', post, class: 'btn btn-secondary'
          = link_to confirm_post_path(post.id),class: 'btn btn-primary', method: :post
            | #{I18n.t(".button.agree")}
          = link_to cancel_post_path(post.id), class: 'btn btn-danger', method: :post
            | #{I18n.t(".button.refuse")}
          = link_to delete_post_path(post), class: 'btn btn-danger', method: :delete
            | #{I18n.t(".button.delete")}
  .row
    .col-md-4
      == pagy_bootstrap_nav(@pagy)